### ISSUE TITLE
Can't allocate ordinary RAM and know its address

### ISSUE THREAD

**Issue by wom-bat** [Ivan-Velickovic/sel4cp#18]
For passthrough devices to a VM, in the absence of an IO MMU, the guest Linux needs to know the physical addresses of its RAM so it can properly set up DMA.

In the examples so far, we've allocated at a fixed address, and tweaked the seL4 device tree to make the RAM at that address invisible to the kernel (so it is allocated as device-untyped).

That doesn't scale: it requires rebuilding the seL4 kernel and microkit tool for every new case.

Alternative solutions could be:
1.  Allow a 1:1 mapping option when allocating normal RAM.  The VMM would then  have to adjust the device tree handed to the guest to reflect the actual RAM allocation (this could be done at build time, as the microkit tool outputs the actual addresses in the report file).  If you could do 'vaddr = paddr' in the `virtual_machine` clause it'd do the trick
2. When allocating a chunk with fixed address, if it's a normal (as opposed to device) memory region, just remove that region from the normal memory region (free space)  in the tool before regions where the address is not assigned are allocated.This requires the system designer to keep track of all memory when building the system XML file, and means that several places need updating every time one wants to change, e.g., the amount of RAM given to a guest.
3. Something else I haven't thought of.

**Comment by wom-bat** [comment]
So I tried a naive implementation of 2. above --- by marking real memory as device early on --- but it fails at run time because the list of caps from the kernel bootinfo doesn't match the calculated one.  Needs to be a but smarter...

**Comment by Ivan-Velickovic** [comment]
Fixed in mainline Microkit.
